### ISSUE TITLE
Can't generate PDF reports

### ISSUE THREAD

**Issue by m4r1oph** [UnauthorizedAccessBV/ESET-Protect-Docker-Server#4]
I'm working also in a docker for ESET Protect and im strugglig with this error, when i want to generate a PDF report it tells me back that is happening a internal error. I have tried somethings but nothing.
Have you had this problem too?

**Comment by dmaasland** [comment]
Hmm, no, it should work out of the box. Can you share how you're running the container and what you are doing to generate the report?

**Comment by m4r1oph** [comment]
Is seems to be a problem with the visor X, because when I try to generate the PDF in the logs of the console shows me that the server can't initialize the X server.
I have tried to make the docker with a GUI interface to make him show me the report.

#DOCKERFILE

![imagen](https://user-images.githubusercontent.com/94112810/162376984-370fb998-0917-4840-8bc0-fbef4c706be3.png)

#DOCKERCOMPOSE

![imagen](https://user-images.githubusercontent.com/94112810/162375419-b7482a0f-afb4-41f8-bf67-5ff96bdb5de1.png)

#HOW I GENERATE THE PDF

![imagen](https://user-images.githubusercontent.com/94112810/162376475-28e6c169-aa9e-4faa-ae26-4c3ba6f5c774.png)

#THE ERROR THAT THE LOG SHOW ME

![imagen](https://user-images.githubusercontent.com/94112810/162377086-9308e9d7-f301-41fe-95a9-55807b3bae23.png)

**Comment by dmaasland** [comment]
Well, it shouldn't need X. It uses a wrapper script and xvfb to accomplish the same thing. See https://github.com/UnauthorizedAccessBV/ESET-Protect-Docker-Server/blob/main/files/ReportPrinterTool. 

However, I can't help but notice that you're not using the docker image from this repository in your compose file. Also, I think you've posted your compose file twice and not the actual Dockerfiles you are using :)

**Comment by m4r1oph** [comment]
Yep I posted the docker-compose twice xd.
Im going to try again your script, and yes im usign my own image.

This is the dockerfile anyway.
 
![imagen](https://user-images.githubusercontent.com/94112810/162382802-1bc545fc-a5bc-412f-b30a-ecd3a096ea2b.png)
